title: Frederic Gosselin # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio :) 
  <br><br>
  I'm a second-year French Canadian software engineering student.
  <br><br>
  <a href="https://goldenweiss.github.io/">View My Github Portfolio</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-372200-0 # your Google Analytics tracking ID here
